frontend_default:
    resource: '@FrontendBundle/Resources/config/routing/default.yml'
    prefix: /

frontend_pages:
    resource: '@PagesBundle/Resources/config/routing.yml'
    prefix: /pages

frontend_user:
    resource: '@UserBundle/Resources/config/routing/frontend.yml'
    prefix: /user

frontend_product:
    resource: '@FrontendBundle/Resources/config/routing/product.yml'
    prefix: /product

frontend_category:
    resource: '@CategoryBundle/Resources/config/routing/frontend.yml'
    prefix: /category

