services:

    tianos.frontend.controller.default:
        class: Bundle\FrontendBundle\Controller\DefaultController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.frontend.controller.default, alias: tianos.frontend.controller.default }

    tianos.frontend.controller.product:
        class: Bundle\FrontendBundle\Controller\ProductController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.frontend.controller.product, alias: tianos.frontend.controller.product }

    tianos.frontend.controller.category:
        class: Bundle\FrontendBundle\Controller\CategoryController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.frontend.controller.category, alias: tianos.frontend.controller.category }

