services:

    tianos.listener.doctrine.product:
        class: Bundle\ProductBundle\EventListener\DoctrineListenerService
        arguments: ["@security.token_storage"]
        tags:
          - { name: doctrine.event_listener, event: postUpdate }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: postLoad }
          - { name: doctrine.event_listener, event: postRemove }


    # *************
    # Product
    tianos.api.controller.product:
        class: Bundle\ProductBundle\Controller\ApiController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.api.controller.product, alias: tianos.api.controller.product }

    tianos.backend.controller.product:
        class: Bundle\ProductBundle\Controller\BackendController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.backend.controller.product, alias: tianos.backend.controller.product }

    tianos.frontend.controller.product:
        class: Bundle\ProductBundle\Controller\FrontendController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.frontend.controller.product, alias: tianos.frontend.controller.product }

    tianos.repository.product:
        class: Dummy
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Bundle\ProductBundle\Entity\Product ]

    tianos.type.product:
        class: Bundle\ProductBundle\Form\Type\ProductType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: tianos.type.product }
    # *************


    # *************
    # Brand
    tianos.backend.controller.brand:
        class: Bundle\ProductBundle\Controller\BrandController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.backend.controller.brand, alias: tianos.backend.controller.brand }

    tianos.repository.brand:
        class: Dummy
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Bundle\ProductBundle\Entity\Brand ]

    tianos.type.brand:
        class: Bundle\ProductBundle\Form\Type\BrandType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: tianos.type.brand }
    # *************




