services:

    tianos.listener.doctrine.category:
        class: Bundle\CategoryBundle\EventListener\DoctrineListenerService
        arguments: ["@security.token_storage"]
        tags:
          - { name: doctrine.event_listener, event: postUpdate }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: postLoad }
          - { name: doctrine.event_listener, event: postRemove }

    tianos.api.controller.category:
        class: Bundle\CategoryBundle\Controller\ApiController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.api.controller.category, alias: tianos.api.controller.category }

    tianos.backend.controller.category:
        class: Bundle\CategoryBundle\Controller\BackendController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.backend.controller.category, alias: tianos.backend.controller.category }

    tianos.frontend.controller.category:
        class: Bundle\CategoryBundle\Controller\FrontendController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.frontend.controller.category, alias: tianos.frontend.controller.category }

    tianos.tree.controller.category:
        class: Bundle\CategoryBundle\Controller\TreeController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.tree.controller.category, alias: tianos.tree.controller.category }

    tianos.repository.category:
        class: Dummy
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Bundle\CategoryBundle\Entity\Category ]

    tianos.type.category:
        class: Bundle\CategoryBundle\Form\Type\CategoryType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: tianos.type.category }


#    TWIG EXTENSION
#    TWIG EXTENSION
    tianos.registry.category_field:
        class: Component\Registry\ServiceRegistry
        arguments: [ Component\Category\FieldTypes\FieldTypeInterface, "grid field" ]

    tianos.form_registry.category_filter:
        class: Bundle\CategoryBundle\Form\Registry\FormTypeRegistry
        public: false

    tianos.expression_language:
        class: Bundle\ResourceBundle\ExpressionLanguage\ExpressionLanguage
        public: false

    tianos.user_options_parser:
        class: Bundle\ResourceBundle\User\Parser\OptionsParser
        arguments: [ "@service_container", "@tianos.expression_language", "@property_accessor" ]
        public: false

    tianos.custom_category_renderer.twig.inner:
        class: Bundle\CategoryBundle\Renderer\TwigCategoryRenderer
        arguments: [ "@twig", "@tianos.registry.category_field", "@form.factory", "@tianos.form_registry.category_filter", SyliusOneToManyBundle::_grid.html.twig ]
        public: false

    tianos.custom_category_renderer.twig:
        class: Bundle\ResourceBundle\Category\Renderer\TwigCategoryRenderer
        arguments: [ "@tianos.custom_category_renderer.twig.inner", "@twig", "@tianos.user_options_parser" ]

    tianos.templating.helper.category:
        class: Bundle\CategoryBundle\Templating\Helper\CategoryHelper
        arguments: [ "@tianos.custom_category_renderer.twig", "@service_container", "@twig" ]

    twig.extension.category:
        class: Bundle\CategoryBundle\Twig\CategoryExtension
        arguments: ['@tianos.templating.helper.category']
        public: false
        tags:
         - { name: twig.extension }







