backend_brand_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.brand:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            roles_allow:
                - ROLE_PRODUCT_VIEW
            vars:
                subheader: sylius.ui.manage_your_role_catalog
                icon: cube
                body_css: grid-body-css
            grid:
                icon: tag
                box_class: primary
                title: Gestionar brand (marca)
                modal:
                    title: Crear brand
                data_table:
                    route:
                        info: backend_brand_info
                        view: backend_brand_view
                        edit: backend_brand_edit
                        create: backend_brand_create
                        delete: backend_brand_delete
                    table_button:
                        #- edit
                        #- delete
                    table_button_header:
                        - create
                        - info
                    table_option:
                        pageLength: 50
                        dom: "'<\"top\"iflp><\"clear\">rt<\"bottom\"iflp>'"
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - obj: " '<span class=\"badge bg-light-blue-active\">' + obj.id + '</span>' "
                          defs:
                              targets: 0
                              searchable: 1
                              sorting: 1
                              orderable: 1
                              type: html
                              width: 4%
                              title: '#'
                              className: modal-view text-center
                        - obj: obj.name
                          defs:
                              targets: 1
                              orderable: 1
                              sorting: 1
                              title: Nombre
                              className: modal-edit
                              filter: 1
                        - obj: obj.created_at
                          defs:
                              targets: 2
                              title: '<i class="fa fa-fw fa-calendar"></i> Creado'
                              className: text-center
            form:
                type: Bundle\ProductBundle\Form\Type\BrandType
            repository:
                service: tianos.repository.brand
                method: findAll
                arguments: [$brandId]
                vars:
                    serialize_group_name: crud

backend_brand_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.brand:createAction
        _tianos:
            action: create
            template: ProductBundle:Brand/Form:form.html.twig
            entity: Bundle\ProductBundle\Entity\Brand
            roles_allow:
                - ROLE_PRODUCT_CREATE
            form:
                type: Bundle\ProductBundle\Form\Type\BrandType
            repository:
                vars:
                    serialize_group_name: crud

backend_brand_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.brand:editAction
        _tianos:
            action: edit
            template: ProductBundle:Brand/Form:form.html.twig
            roles_allow:
                - ROLE_PRODUCT_EDIT
            form:
                type: Bundle\ProductBundle\Form\Type\BrandType
            repository:
                service: tianos.repository.brand
                method: find
                arguments: [$brandId]
                vars:
                    serialize_group_name: crud

backend_brand_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.backend.controller.brand:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            roles_allow:
                - ROLE_PRODUCT_DELETE
            repository:
                service: tianos.repository.brand
                method: find
                arguments: [$brandId]
            vars:
#                body_css: grid-body-css

backend_brand_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.brand:viewAction
        _tianos:
            action: view
            template: ProductBundle:Brand/Informative:view.html.twig
            roles_allow:
                - ROLE_PRODUCT_VIEW
            repository:
                service: tianos.repository.brand
                method: find
                arguments: [$brandId]
                vars:
                    serialize_group_name: crud

backend_brand_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.brand:infoAction
        _tianos:
            action: info
            template: ProductBundle:Brand/Informative:info.html.twig